[project]
name = "numerical-methods-example"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "ipython>=9.6.0",
    "matplotlib>=3.10.6",
    "nbconvert>=7.16.6",
    "numpy>=2.3.3",
    "scipy>=1.16.2",
]
